---

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
    Pint\NewsPage\:
        resource: ../Classes/*
    Pint\NewsPage\DataProcessing\NewsPageProcessor:
        public: true
    Pint\NewsPage\Hooks\DataHandlerHook:
        public: true
    Pint\NewsPage\Hooks\DatabaseRecordListHook:
        public: true
